# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip Install flask

# Make port 5000 available to the worldoutside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]